version: "3.9"


services:
  minio:
    image: minio/minio
    container_name: minio-server
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:15
    container_name: postgres-warehouse
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: warehouse

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d warehouse"]
      interval: 5s
      timeout: 5s
      retries: 60

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://admin:password123@postgres:5432/warehouse
      --default-artifact-root /mlflow/artifacts
    environment:
      MLFLOW_ALLOW_HOSTS: "*"
      
    volumes:
      - ./mlruns:/mlflow/artifacts
    depends_on:
      - postgres

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  pipeline:
    build: .
    container_name: pipeline
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      # mlflow:
      #   condition: service_healthy





volumes:
  minio_data:
  postgres_data: